executors:
  cypress:
    docker:
      - image: cypress/base:12
        environment:
          TERM: xterm
    working_directory: ~/agent-tracker

commands:
  restore_yarn_install:
    steps:
      - restore_cache:
          name: Restore Cache [yarn install]
          key: yarn-modules-{{ checksum "yarn.lock" }}
  restore_cypress_install:
    steps:
      - restore_cache:
          name: Restore Cache [cypress]
          key: cypress-{{ checksum "yarn.lock" }}
  yarn_install:
    steps:
      - run:
          name: Install dep
          command: yarn install

orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.2.6


version: 2.1
jobs:
  checkout_code:
    executor: cypress
    steps:
      - checkout
      - restore_yarn_install
      - restore_cypress_install
      - yarn_install
      - save_cache:
          key: yarn-modules-{{ checksum "yarn.lock"}}
          paths:
            - ./node_modules
      - save_cache:
          key: cypress-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
  test_and_ts_check:
    executor: cypress
    steps:
      - checkout
      - restore_yarn_install
      - run: yarn ts:check && yarn test
  build:
    executor: cypress
    steps:
      - checkout
      - restore_yarn_install
      - run:
          name: Build agent-tracker
          command: yarn build
      - save_cache:
          key: agent-tracker
          paths:
            - ./build
  heroku_deploy:
    working_directory: ~/agent-tracker
    executor: cypress
    steps:
      - checkout
      - attach_workspace:
          at: ~/agent-tracker
      - heroku/deploy-via-git


workflows:
  version: 2
  main:
    jobs:
      - checkout_code
      - test_and_ts_check:
          requires:
            - checkout_code
      - build:
          name: build_agent_tracker
          requires:
            - checkout_code
      - heroku_deploy:
          requires:
            - build
          filters:
            branches:
              only: FE-3